apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 1000
      containers:
        - name: jenkins
          image: bodukal/jenkins-docker:latest
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
            - name: docker-graph-storage
              mountPath: /var/lib/docker
          env:
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2375 # Explicitly use 127.0.0.1 instead of localhost
        - name: docker
          image: docker:24-dind
          securityContext:
            privileged: true
          args:
            - --host=tcp://0.0.0.0:2375
            - --tls=false # Disable TLS for simplicity (secure in production if needed)
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
        - name: docker-graph-storage
          emptyDir: {}
