apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ecomm-monitor
  namespace: default
  labels:
    app: ecomm
    release: prometheus
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ecomm
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
    scrapeTimeout: 10s
